services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_CONSUMER_TIMEOUT: 0
        networks:
            - rabbitmq-network
            - techcommerce-network
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_logs:/var/log/rabbitmq

    notification-db:
        image: redis:7
        container_name: notification-db
        networks:
            - techcommerce-network
        volumes:
            - redis_data:/data

    kong-database:
        image: postgres:15
        container_name: kong-database
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        networks:
            - kong-network
        volumes:
            - kong_db_data:/var/lib/postgresql/data

    kong:
        image: kong/kong-gateway:3.9.0.1
        container_name: kong
        depends_on:
            kong-database:
                condition: service_healthy
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kong
            KONG_PG_DATABASE: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
            - 8002:8002
            - 8445:8445
            - 8003:8003
            - 8004:8004
        networks:
            - kong-network
            - techcommerce-network
        volumes:
            - kong_config:/etc/kong
        command: >
            sh -c "kong migrations bootstrap &&
                  kong config db_import /etc/kong/kong.yml &&
                  kong start"

networks:
    techcommerce-network:
        name: techcommerce-network
        driver: bridge
    rabbitmq-network:
        name: rabbitmq-network
        driver: bridge
    kong-network:
        name: kong-network
        driver: bridge

volumes:
    rabbitmq_data:
        name: rabbitmq_data
    rabbitmq_logs:
        name: rabbitmq_logs
    redis_data:
        name: redis_data
    kong_db_data:
        name: kong_db_data
    kong_config:
        name: kong_config
