services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
        networks:
            - techcommerce-network

    notification-db:
        image: redis:7
        container_name: notification-db
        networks:
            - techcommerce-network
        volumes:
            - redis_data:/data

    kong-database:
        image: postgres:13
        container_name: kong-database
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        networks:
            - kong-network

    kong:
        image: kong/kong-gateway:3.9.0.1
        container_name: kong
        depends_on:
            kong-database:
                condition: service_healthy
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kong
            KONG_PG_DATABASE: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_PLUGINS: bundled,cors
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
            - 8002:8002
            - 8445:8445
            - 8003:8003
            - 8004:8004
        networks:
            - techcommerce-network
            - kong-network
        volumes:
            - ./kong.yml:/etc/kong/kong.yml:ro
        command: >
            sh -c "kong migrations bootstrap &&
                  kong config db_import /etc/kong/kong.yml &&
                  kong start"

    swagger:
        image: swaggerapi/swagger-ui:v5.20.1
        container_name: swagger
        depends_on:
            - kong
        environment:
            URLS: "[{ name: 'Identity', url: 'http://localhost:8000/identity/api-docs' }"
        ports:
            - 80:8080
        networks:
            - techcommerce-network
            - kong-network

networks:
    techcommerce-network:
        name: techcommerce-network
        driver: bridge
    kong-network:
        name: kong-network
        driver: bridge

volumes:
    redis_data:
        name: redis_data
