services:
    kong-database:
        image: postgres:15
        container_name: kong-database
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        networks:
            - kong-network
        volumes:
            - kong_db_data:/var/lib/postgresql/data

    kong:
        image: kong/kong-gateway:3.9.0.1
        container_name: kong
        depends_on:
            kong-database:
                condition: service_healthy
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_PASSWORD: kong
            KONG_PG_DATABASE: kong
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
            - 8002:8002
            - 8445:8445
            - 8003:8003
            - 8004:8004
        networks:
            - kong-network
            - techcommerce-network
        volumes:
            - kong_config:/etc/kong
        command: >
            sh -c "kong migrations bootstrap &&
                  kong config db_import /etc/kong/kong.yml &&
                  kong start"
    # swagger: 
    #     image: swaggerapi/swagger-ui
    #     container_name: swagger
    #     environment:
    #         URL: http://host.docker.internal:8081/catalog/api-docs
    #     ports:
    #         - 80:8080


networks:
    techcommerce-network:
        name: techcommerce-network
        driver: bridge
    kong-network:
        name: kong-network
        driver: bridge

volumes:
    kong_db_data:
        name: kong_db_data
    kong_config:
        name: kong_config
