services:
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        networks:
            - techcommerce-network
        volumes:
            - ./infra/databases/init.development.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            retries: 5

    kong:
        volumes:
            - ./services/gateway/kong.development.yml:/etc/kong/kong.yml:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
