services:
    email-service:
        image: techcommerce/email-service:1.0.0
        container_name: email-service
        build:
            context: ./services/email
            dockerfile: Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            EMAIL_USER: ${EMAIL_USER}
            EMAIL_PASS: ${EMAIL_PASS}
        networks:
            - techcommerce-network
        env_file:
            - .env
        command: ["bun", "run", "dist/index.js"]

    identity-db:
        image: postgres:15
        container_name: identity-db
        environment:
            POSTGRES_USER: ${IDENTITY_DB_USER}
            POSTGRES_PASSWORD: ${IDENTITY_DB_PASS}
            POSTGRES_DB: ${IDENTITY_DB_NAME}
        networks:
            - techcommerce-network

    product-db:
        image: postgres:15
        container_name: product-db
        environment:
            POSTGRES_USER: ${PRODUCT_DB_USER}
            POSTGRES_PASSWORD: ${PRODUCT_DB_PASS}
            POSTGRES_DB: ${PRODUCT_DB_NAME}
        networks:
            - techcommerce-network

    order-db:
        image: postgres:15
        container_name: order-db
        environment:
            POSTGRES_USER: ${ORDER_DB_USER}
            POSTGRES_PASSWORD: ${ORDER_DB_PASS}
            POSTGRES_DB: ${ORDER_DB_NAME}
        networks:
            - techcommerce-network

    payment-db:
        image: postgres:15
        container_name: payment-db
        environment:
            POSTGRES_USER: ${PAYMENT_DB_USER}
            POSTGRES_PASSWORD: ${PAYMENT_DB_PASS}
            POSTGRES_DB: ${PAYMENT_DB_NAME}
        networks:
            - techcommerce-network

    kong:
        volumes:
            - ./services/gateway/kong.prod.yml:/etc/kong/kong.yml:ro
